ShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user')),
    path('', include('products.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views
from .api import views as apiviews
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'products', apiviews.ProductViewSet)
router.register(r'attributes', apiviews.AttributeViewSet)
router.register(r'tags', apiviews.TagViewSet)
router.register(r'brands', apiviews.BrandViewSet)
router.register(r'categories', apiviews.CategoryViewSet)

app_name = 'shop'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='home'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('add-to-cart/<int:pk>/', views.AddToCart.as_view(), name='add_to_cart'),
    path('create-comment/', views.CreateCommentView.as_view(), name='create_comment'),
    path('cart/', views.CartItemView.as_view(), name='cart'),
    path('plus-cart/<int:pk>/', views.plus_cart, name='plus_cart'),
    path('minus-cart/<int:pk>/', views.minus_cart, name='minus_cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('send-sms/', views.send_sms, name='send_sms'),
    #api

    ] + router.urls

users/urls.py
from django.urls import path, reverse_lazy
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from .api import views as apiviews
from . import views

# router = DefaultRouter()
# router.register(r'supplier', apiviews.SupplierViewSet)

app_name = 'user'
urlpatterns =[
    path('login/', views.AuthenticationView.as_view(), name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register-customer/', views.RegisterCustomerView.as_view(), name='register_customer'),
    path('register-supplier/', views.RegisterSupplierView.as_view(), name='register_supplier'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
    path('update-supplier/<int:pk>/', views.UpdateSupplierView.as_view(), name='update_supplier'),
    path('update-customer/<int:pk>/', views.UpdateCustomerView.as_view(), name='update_customer'),
    
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('set-password/<token>/', views.PasswordResetVerifyView.as_view(), name='set_password'),
    # api
    path('signup-supplier/', apiviews.RegisterSupllierApiView.as_view(), name='sugnup_supplier'),
    path('signup-customer/', apiviews.RegisterCustomerApiView.as_view(), name='sugnup_customer'),
    path('change-password-api/', apiviews.ChangePassowrd.as_view(), name='change_passwordr_api'),
    path('reset-password-api/', apiviews.ResetPasswordApiView.as_view(), name='reset_passwordr_api'),
    path('set-password-api/<token>/', apiviews.SetPasswordApiView.as_view(), name='set_password_api'),


    path('profile/', apiviews.SupplierView.as_view(), name='sugnup_supplier'),
    path('login-api/', obtain_auth_token, name='login_api')
]


# urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

templates/extends/base.html
<!DOCTYPE html>
<html lang="en">
    {% include 'extends/head.html' %}

    <body>
        {% comment %}{% include 'extends/top-bar.html' %} {% endcomment %}

        {% include 'extends/header.html' %}

        {% include 'extends/buttom_bar_start.html' %}

        {% block content %}

        {% endblock %}

        {% include 'extends/footer.html' %}

        {% include 'extends/script.html' %}
    </body>
</html>

templates/extends/buttom_bar_start.html
{% load static %}

<!-- Bottom Bar Start -->
<div class="bottom-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-3">
                <div class="logo">
                    <a href="index.html">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <input type="text" placeholder="Search">
                    <button><i class="fa fa-search"></i></button>
                </div>
            </div>
            <div class="col-md-3">
                <div class="user">
                    <!-- <a href="wishlist.html" class="btn wishlist">
                        <i class="fa fa-heart"></i>
                        <span>(0)</span>
                    </a> -->
                    {% if request.cart %}
                    <a href="{% url 'shop:cart' %}" class="btn cart">
                        <i class="fa fa-shopping-cart"></i>
                        <span>{{ request.cart|length }}</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Bottom Bar End --> 

templates/extends/footer.html
{% load static %}
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        


<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-6 copyright">
                <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
            </div>

            <div class="col-md-6 template-by">
                <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
            </div>
        </div>
    </div>
</div>

<!-- Back to Top -->
<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/extends/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <title>E Store - eCommerce HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="eCommerce HTML Template Free Download" name="keywords">
    <meta content="eCommerce HTML Template Free Download" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
    <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Profile Scripts -->
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
</head>

templates/extends/header.html
{% load static %}

<style>
.nowrap {
    white-space: nowrap ;
  }
</style>
<!-- Nav Bar Start -->
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
      {{message}}
    </div>
    {% endfor %}
{% endif %}
<div class="nav">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a href="#" class="navbar-brand">MENU</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav mr-auto">
                    <!-- <a href="index.html" class="nav-item nav-link">Home</a> -->
                    <a href="{% url 'shop:home' %}" class="nav-item nav-link">Products</a>
                    <a href="{% url 'shop:cart' %}" class="nav-item nav-link">Cart</a>
                    <!-- <a href="{% url 'shop:add_to_cart' 1 %}" class="nav-item nav-link">Checkout</a> -->
                    <!-- <a href="wishlist.html" class="nav-item nav-link">Wishlist</a> -->
                    <!-- <a href="contact.html" class="nav-item nav-link">Contact Us</a> -->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle active" data-toggle="dropdown">User Pages</a>
                        <div class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <div class="container mt-5 d-flex justify-content-center">
                                    <div class="card p-3">
                                        <div class="d-flex align-items-center">
                                            <div class="image"> <img src="{{request.user.profile_picture.url}}" class="rounded" width="155"> </div>
                                            <div class="ml-3 w-100">
                                                {% if request.user.first_name and request.user.last_name%}
                                                    <h4 class="mb-0 mt-0 nowrap">{{ request.user.first_name }} {{ request.user.last_name }}</h4> <span>{{ request.session.type }}</span>
                                                {% else %}
                                                    <h4 class="mb-0 mt-0 nowrap">{{ request.user.username }}</h4> <span>{{ request.session.type }}</span>
                                                {% endif %}
                                                <!-- <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                                                    <div class="d-flex flex-column"> <span class="articles">Articles</span> <span class="number1">38</span> </div>
                                                    <div class="d-flex flex-column"> <span class="followers">Followers</span> <span class="number2">980</span> </div>
                                                    <div class="d-flex flex-column"> <span class="rating">Rating</span> <span class="number3">8.9</span> </div>
                                                </div> -->
                                                <div class="button mt-2 d-flex flex-row align-items-center">
                                                    {% if request.user.is_customer %}
                                                        <a href="{% url 'user:update_customer' request.user.pk %}">
                                                            <button class="btn btn-sm btn-outline-primary w-100 nowrap">My Account</button>
                                                        </a>
                                                    {% elif request.user.is_supplier %}
                                                        <a href="{% url 'user:update_supplier' request.user.pk %}">
                                                            <button class="btn btn-sm btn-outline-primary w-100 nowrap">My Account</button>
                                                        </a>
                                                    {% endif %}
                                                    <a href="{% url 'user:logout' %}" >
                                                        <button class="btn btn-sm btn-primary w-100 ml-2">Logout</button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'user:login' %}" class="dropdown-item">Login</a>
                                <a href="{% url 'user:register_supplier' %}" class="dropdown-item">Register Supplier</a>
                                <a href="{% url 'user:register_customer' %}" class="dropdown-item">Register Customer</a>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Nav Bar End --> 

templates/extends/script.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/slick/slick.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'lib/slick/main.js' %}"></script>

<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js'></script>

templates/extends/side-bar.html
                    <!-- Side Bar Start -->
                    <div class="col-lg-4 sidebar">
                        <div class="sidebar-widget category">
                            <h2 class="title">Category</h2>
                            <nav class="navbar bg-light">
                                <ul class="navbar-nav">
                                    {% for cat in categories %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="?cat={{cat.pk}}"><i class="fa fa-female"></i>{{cat.cat_name}}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </nav>
                        </div>
                        
                        
                        <div class="sidebar-widget brands">
                            <h2 class="title">Our Brands</h2>
                            <ul>
                                {% for brand in brands %}
                                <li><a href="?brand={{brand.pk}}">{{brand.brand_name}} </a><span>{{brand.get_product_number}}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                        
                        <div class="sidebar-widget tag">
                            <h2 class="title">Tags Cloud</h2>
                            {% for tag in tags %}
                                <a href="?tag={{tag.pk}}">{{tag}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Side Bar End -->

templates/extends/top-bar.html
<!-- Top bar Start -->
<div class="top-bar">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <i class="fa fa-envelope"></i>
                support@email.com
            </div>
            <div class="col-sm-6">
                <i class="fa fa-phone-alt"></i>
                +012-345-6789
            </div>
        </div>
    </div>
</div>
<!-- Top bar End -->