ShopProject/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user')),
    path('', include('products.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from rest_framework.urlpatterns import format_suffix_patterns

from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from .api import views as apiviews
from . import views

# router = DefaultRouter()
# router.register(r'supplier', apiviews.SupplierViewSet)

app_name = 'user'
urlpatterns =[
    path('login/', views.AuthenticationView.as_view(), name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('register-customer/', views.RegisterCustomerView.as_view(), name='register_customer'),
    path('register-supplier/', views.RegisterSupplierView.as_view(), name='register_supplier'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
    path('update-supplier/<int:pk>/', views.UpdateSupplierView.as_view(), name='update_supplier'),
    path('update-customer/<int:pk>/', views.UpdateCustomerView.as_view(), name='update_customer'),
    
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('set-password/<token>/', views.PasswordResetVerifyView.as_view(), name='set_password'),
    # api
    path('signup-supplier/', apiviews.RegisterSupllierApiView.as_view(), name='sugnup_supplier'),
    path('signup-customer/', apiviews.RegisterCustomerApiView.as_view(), name='sugnup_customer'),
    path('change-password-api/', apiviews.ChangePassowrd.as_view(), name='change_passwordr_api'),
    path('reset-password-api/', apiviews.ResetPasswordApiView.as_view(), name='reset_passwordr_api'),
    path('set-password-api/<token>/', apiviews.SetPasswordApiView.as_view(), name='set_password_api'),


    path('profile/', apiviews.SupplierView.as_view(), name='sugnup_supplier'),
    path('login-api/', obtain_auth_token, name='login_api')
]


# urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth.models import Group
from django.contrib import messages

from .models import Supplier, Customer,User


class CustomAuthenticationForm(AuthenticationForm):
    LOGIN_CHOICES = (
        ('C', 'Customer'),
        ('S', 'Supplier'),
        ('A', 'Admin'),
    )
    login_choices = forms.ChoiceField(choices=LOGIN_CHOICES)
    
    def clean(self):
        super().clean()
        choice = self.cleaned_data.get('login_choices')
        if choice == 'C':
            try:
                Customer.objects.get(username=self.cleaned_data.get('username'))
                self.request.session['type'] = 'customer'
            except Exception as e:
                raise ValidationError(e)
        if choice == 'S':
            try:
                Supplier.objects.get(username=self.cleaned_data.get('username'))
                self.request.session['type'] = 'supplier'
            except Exception as e:
                raise ValidationError(e)
        if choice == 'A':
            self.request.session['type'] = 'admin'
        return self.cleaned_data


class RegisterSupplierForm(UserCreationForm):
    '''
    using UserCreationForm for our model.
    '''
    class Meta(UserCreationForm.Meta):
        model = Supplier
        # You should Override fields base on your Customize model
        fields = [
            'username', 'password1', 'password2', 'first_name',
            'last_name', 'email', 'company_name', 'bank_account',
            'profile_picture']

    def save(self, *args, **kargs):
        '''
        assign user_type to supplier type before saving
        '''
        supplier =  super().save(*args, **kargs)
        supplier.is_admin = True
        group = Group.objects.get(name='Supplier-Permissions')
        supplier.groups.add(group)
        supplier.save()
        return supplier


class RegisterCustomerForm(UserCreationForm):
    '''
    using UserCreationForm for our model.
    '''
    class Meta(UserCreationForm.Meta):
        model = Customer
        # You should Override fields base on your Customize model
        fields = [
            'username', 'password1', 'password2', 'first_name',
            'last_name', 'email', 'phone', 'gender', 'profile_picture']


class SupplierProfileForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['username', 'first_name', 'last_name', 'email', 'bank_account', 'company_name']


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'gender']

class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )


class SetPasswordForm(forms.Form):
    password1 = forms.CharField(max_length=40, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=40, widget=forms.PasswordInput())

users/api/views.py
from django.core.mail import send_mail
from django.conf import settings

from rest_framework.generics import CreateAPIView, GenericAPIView, RetrieveUpdateDestroyAPIView, UpdateAPIView
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet, ViewSet, GenericViewSet
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.mixins import (
    CreateModelMixin, RetrieveModelMixin,
    UpdateModelMixin, DestroyModelMixin,
    ListModelMixin)

import redis
import secrets
import json

from users.models import Supplier, Customer, User
from .serializers import (RegisterSupplierSerializer, RegisterCustomerSerializer,
                          UpdateSupplierSerializer, UpdateCustomerSerializer,
                          ChangePassswordSerializer, ResetPasswordSerializer,
                          SetPasswordSerializer)


class SupplierView(RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = Supplier.objects.filter(pk=self.request.user.pk)
        if user:
            return Supplier.objects.all()
        return Customer.objects.all()

    def get_object(self, *args, **kwargs):
        return self.get_queryset().get(pk=self.request.user.pk)

    def get_serializer_class(self):
        user = Supplier.objects.filter(pk=self.request.user.pk)
        if user:
            return UpdateSupplierSerializer
        else:
            return UpdateCustomerSerializer


class ChangePassowrd(UpdateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = User.objects.all()
    serializer_class = ChangePassswordSerializer

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

class RegisterSupllierApiView(CreateAPIView):
    serializer_class = RegisterSupplierSerializer


class RegisterCustomerApiView(CreateAPIView):
    serializer_class = RegisterCustomerSerializer


class ResetPasswordApiView(APIView):
    serializer_class = ResetPasswordSerializer
    def post(self, request):
        serilizered_data = self.serializer_class(data=request.data)
        if serilizered_data.is_valid():
            r = redis.Redis(host='localhost', port=6379, db=0)
            token = secrets.token_urlsafe(16)
            email = serilizered_data.data['email']
            r.set(token, email, ex=60*40)
            message = f'for resetting your password send your new \
                 and confirm password with post method to \
                <a href="http://localhost:8000/user/set_password_api/{token}/">here</a>'

            send_mail(
                'ResetPassword',
                message,
                settings.EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )
            r.close()
        return Response("Go and Check your email")


class SetPasswordApiView(APIView):
    serializer_class = SetPasswordSerializer

    def post(self, request, token):
        serilized_data = self.serializer_class(data=request.data)
        if serilized_data.is_valid():
            r = redis.Redis(host='localhost', port=6379, db=0)
            print(type(r.get(token)))
            mail = r.get(token).decode('utf-8')
            print(mail)
            user = User.objects.get(email=mail)
            print(serilized_data.validated_data['password1'])
            user.set_password(serilized_data.validated_data['password1'])
            user.save()
            return Response(serilized_data.validated_data, status=status.HTTP_200_OK)
        
        return Response(serilized_data.errors, status=status.HTTP_400_BAD_REQUEST)
        
        

users/views.py
import os
import secrets
from pathlib import Path

from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm,
    )
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import send_mail
from django.conf import settings

import redis
from dotenv import load_dotenv, find_dotenv

from .forms import (RegisterSupplierForm, RegisterCustomerForm, PasswordResetForm,
    CustomerProfileForm, SupplierProfileForm,
    SupplierProfileForm, CustomerProfileForm,
    SetPasswordForm, CustomAuthenticationForm)
from .models import User
from .models import Customer, Supplier

env_file = Path(find_dotenv(usecwd=True))
load_dotenv(verbose=True, dotenv_path=env_file)


class AuthenticationView(LoginView):
    template_name = 'authentication/login.html'
    form_class = CustomAuthenticationForm
    
    def get_success_url(self):
        return reverse_lazy('shop:home')


def logout_page(request):
    logout(request)
    return redirect(reverse_lazy('user:login'))


class RegisterSupplierView(CreateView):
    form_class = RegisterSupplierForm
    template_name = 'authentication/signup.html'
    success_url = reverse_lazy('user:login')


class RegisterCustomerView(CreateView):
    form_class = RegisterCustomerForm
    template_name = 'authentication/signup.html'
    success_url = reverse_lazy('user:login')


class ChangePassword(PasswordChangeView):
    template_name = 'authentication/change-password.html'
    success_url = reverse_lazy('shop:home')
    form_class = PasswordChangeForm


class UpdateSupplierView(UpdateView):
    model = Supplier
    template_name = 'authentication/update-profile.html'
    form_class = SupplierProfileForm
    success_url = reverse_lazy('shop:home')


class UpdateCustomerView(UpdateView):
    model = Customer
    template_name = 'authentication/update-profile.html'
    form_class = CustomerProfileForm
    success_url = reverse_lazy('shop:home')


class PasswordResetView(View):
    def get(self, request):
        form = PasswordResetForm()
        return render(request, 'authentication/password-reset-form.html', {'form': form})
    
    def post(self,request):
        email = request.POST.get('email')
        r = redis.Redis(host='localhost', port=6379, db=0)
        token = secrets.token_urlsafe(16)
        r.set(token, email, ex=60*5)
        if settings.DEBUG:
            link = f'http://localhost:8000{reverse_lazy("user:set_password", kwargs={"token":token})}/',
        else:
            link = f'http://{os.environ.get("HOST_NAME")}:8000{reverse_lazy("user:set_password", kwargs={"token":token})}/',
        
        send_mail(
            'Reset Password',
            link,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        r.close()
        return render(request, 'authentication/password-reset-done.html')


class PasswordResetVerifyView(View):
    def get(self, request, token):
        r = redis.Redis(host='localhost', port=6379, db=0)
        mail = r.get(token).decode('utf-8')
        form = SetPasswordForm()

        context = {
            'form': form,
            'mail': mail
        }
        return render(request, 'authentication/password-reset-verify.html', context)
        
    def post(self, request, token):
        pas1 = request.POST.get('password1')
        pas2 = request.POST.get('password2')
        mail = request.POST.get('mail')
        user = User.objects.get(email = mail)
        if pas1 == pas2:
            user.set_password(pas1)
            return redirect(reverse_lazy('shop:home'))
        return redirect(reverse_lazy('user:set_password'))

users/templates/authentication/change-password.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}
    
    
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <!-- <div class="col-lg-6">    
                        <div class="register-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>First Name</label>
                                    <input class="form-control" type="text" placeholder="First Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Last Name"</label>
                                    <input class="form-control" type="text" placeholder="Last Name">
                                </div>
                                <div class="col-md-6">
                                    <label>E-mail</label>
                                    <input class="form-control" type="text" placeholder="E-mail">
                                </div>
                                <div class="col-md-6">
                                    <label>Mobile No</label>
                                    <input class="form-control" type="text" placeholder="Mobile No">
                                </div>
                                <div class="col-md-6">
                                    <label>Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-6">
                                    <label>Retype Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-lg-6">
                        <div class="login-form">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {{form.as_p}}
                                    <div class="col-md-12">
                                        <button class="btn">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}
        

users/templates/authentication/login.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}
 
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>E-mail / Username</label>
                                        {{form.username}}
                                    </div>
                                    <div class="col-md-6">
                                        <label>Password</label>
                                        {{form.password}}
                                    </div>
                                    <div class="col-md-6">
                                        <label>Login Choices</label>
                                        {{form.login_choices}}
                                    </div>
                                    <div class="col-md-12">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="newaccount">
                                            <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn">Submit</button>
                                    </div>
                                    <br>
                                </div>
                            </form>
                            <label>Are You an Idiot that forget his/her password?</label>
                            <a href="{% url 'user:reset_password' %}"><button class="btn">Yes i'm soo stupid</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}
        

users/templates/authentication/password-reset-done.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}

        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <p>Check Your inbox, your email has been sended.
            it will expire in  minutes so hurry bitch.
        </p>
{% endblock %}
        

users/templates/authentication/password-reset-form.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}
             

        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <!-- <div class="col-lg-6">    
                        <div class="register-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>First Name</label>
                                    <input class="form-control" type="text" placeholder="First Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Last Name"</label>
                                    <input class="form-control" type="text" placeholder="Last Name">
                                </div>
                                <div class="col-md-6">
                                    <label>E-mail</label>
                                    <input class="form-control" type="text" placeholder="E-mail">
                                </div>
                                <div class="col-md-6">
                                    <label>Mobile No</label>
                                    <input class="form-control" type="text" placeholder="Mobile No">
                                </div>
                                <div class="col-md-6">
                                    <label>Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-6">
                                    <label>Retype Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-lg-6">
                        <div class="login-form">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {{form.as_p}}
                                    <div class="col-md-12">
                                        <button class="btn">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}
        

users/templates/authentication/password-reset-verify.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}
             

        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <!-- <div class="col-lg-6">    
                        <div class="register-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>First Name</label>
                                    <input class="form-control" type="text" placeholder="First Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Last Name"</label>
                                    <input class="form-control" type="text" placeholder="Last Name">
                                </div>
                                <div class="col-md-6">
                                    <label>E-mail</label>
                                    <input class="form-control" type="text" placeholder="E-mail">
                                </div>
                                <div class="col-md-6">
                                    <label>Mobile No</label>
                                    <input class="form-control" type="text" placeholder="Mobile No">
                                </div>
                                <div class="col-md-6">
                                    <label>Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-6">
                                    <label>Retype Password</label>
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="col-md-12">
                                    <button class="btn">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-lg-6">
                        <div class="login-form">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {{form.as_p}}
                                    <input type="hidden" value="{{mail}}" name='mail'>
                                    <div class="col-md-12">
                                        <button class="btn">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}
        

users/templates/authentication/signup.html
{% extends 'extends/base.html' %}
{% block content %}
{% load static %}
       

        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Login & Register</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Login Start -->
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    {{form.as_p}}
                                    <div class="col-md-12">
                                        <button class="btn">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Login End -->
{% endblock %}
        